-- sorry guys we wanted make open source but i think when we release 5.0.1 we make open source
-- version : 3.2.2

--[[
    .___                /\      /\     .___                                 
  __| _/_______  __    / /     / /   __| _/_ __  _____ ______   ___________ 
 / __ |/ __ \  \/ /   / /     / /   / __ |  |  \/     \\____ \_/ __ \_  __ \
/ /_/ \  ___/\   /   / /     / /   / /_/ |  |  /  Y Y  \  |_> >  ___/|  | \/
\____ |\___  >\_/   / /     / /    \____ |____/|__|_|  /   __/ \___  >__|   
     \/    \/       \/      \/          \/           \/|__|        \/       

WARNING: USED MAX. OBFUSCATION. SCRIPT CAN LAG OR JUST DOESNT START
YOU WAS WARNED
By : Onetap Team
Crack By : cazer/hvhash8
--]]
-- pending to fixes!!!!
